version: 2.1
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: mkdir -p buil && cd build
      - run: cmake ..
      - run: cmake --build . --config Release
