version: 2.1
jobs:
  build:
    docker:
      - image: dockerben/cpptemplate:latest
    steps:
      - checkout
      - run: ./../../vcpkg/vcpkg install fmt doctest
      - run: mkdir -p build && cd build && mkdir -p Test
      - run: cd build && cmake -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake .. && cmake --build . --config Release
      - run: cd build && ctest --no-compress-output -T Test
      - run: python3 buildutils/ctest2JUnit.py build buildutils/CTest2JUnit.xsl > build/Test/results.xml #https://stackoverflow.com/questions/6329215/how-to-get-ctest-results-in-hudson-jenkins
      - store_test_results:
          path: build/Test

workflows:
  version: 2
  build:
    jobs:
      - build:
        branches:
            ignore:
              - gh-pages
