name: Generate Documentation

on:
  pull_request:
    branches: 
      - master
  page_build:
      

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: mattnotmitt/doxygen-action@v1
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          doxyfile-path: ./Doxyfile
