name: Generate Documentation

on:
  pull_request:
    branches: 
      - master
  page_build:
      

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
    - uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: # default is ./Doxyfile
